services:
  mysql_8:
    image: mysql:8.0.42
    container_name: mysql_classicmodels
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: classicmodels
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - ./classicmodels.sql:/docker-entrypoint-initdb.d/classicmodels.sql
      - ~/code/data/mysql_8_data:/var/lib/mysql

  postgres_10:
    image: postgres:10.23-bullseye
    container_name: postgres_classicmodels
    restart: always
    environment:
      POSTGRES_DB: classicmodels
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/code/data/pg_10_data:/var/lib/postgresql/data

  postgres_17:
    image: postgres:17.5-bullseye
    container_name: postgres_classicmodels_17
    restart: always
    environment:
      POSTGRES_DB: classicmodels
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5433:5432"
    volumes:
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/code/data/pg_17_data:/var/lib/postgresql/data

volumes:
  mysql_8_data:
  pg_10_data:
  pg_17_data: